export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_FORGOT_PASSWORD_REQUEST = 'GET_FORGOT_PASSWORD_REQUEST'
export const GET_FORGOT_PASSWORD_SUCCESS = 'GET_FORGOT_PASSWORD_SUCCESS'
export const GET_FORGOT_PASSWORD_FAILED = 'GET_FORGOT_PASSWORD_FAILED'

export const GET_RESET_PASSWORD_REQUEST = 'GET_RESET_PASSWORD_REQUEST'
export const GET_RESET_PASSWORD_SUCCESS = 'GET_RESET_PASSWORD_SUCCESS'
export const GET_RESET_PASSWORD_FAILED = 'GET_RESET_PASSWORD_FAILED'

export const GET_REGISTER_USER_REQUEST = 'GET_REGISTER_USER_REQUEST'
export const GET_REGISTER_USER_SUCCESS = 'GET_REGISTER_USER_SUCCESS'
export const GET_REGISTER_USER_FAILED = 'GET_REGISTER_USER_FAILED'

export const GET_LOGIN_USER_REQUEST = 'GET_LOGIN_USER_REQUEST'
export const GET_LOGIN_USER_SUCCESS = 'GET_LOGIN_USER_SUCCESS'
export const GET_LOGIN_USER_FAILED = 'GET_LOGIN_USER_FAILED'

export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAILED = 'GET_USER_DATA_FAILED'

export const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST'
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS'
export const UPDATE_USER_DATA_FAILED = 'UPDATE_USER_DATA_FAILED'

export const CHECK_REFRESH_TOKEN_REQUEST = 'CHECK_REFRESH_TOKEN_REQUEST'
export const CHECK_REFRESH_TOKEN_SUCCESS = 'CHECK_REFRESH_TOKEN_SUCCESS'
export const CHECK_REFRESH_TOKEN_FAILED = 'CHECK_REFRESH_TOKEN_FAILED'
